### ISSUE TITLE
корень всех бед

### ISSUE THREAD

**Issue by logogriph2** [Cognigraph/cognigraph#33]
Есть ли в произвольном узле указатель на корень? Если да, то в какой момент он начинает указывать на источник?
Если в функцию __init__ класса ProcessorNode добавить print('ROOT', self._root), то в результате выполнения в консоль запишется
ROOT Preprocessing

**Comment by logogriph2** [comment]
Если я там же вывожу print('PARENT', self._parent), то получаю PARENT None. То есть предок ещё не был инициализирован. Тогда получается, что обращение на _root можно запускать только начиная с initialize ?

**Comment by dmalt** [comment]
При добавлении родительского узла дочерний узел берет значение корня у родительского. Корень всех узлов начинает указывать на источник, когда все узлы были присоединены друг к другу. Для этого не нужна инициализация

**Comment by logogriph2** [comment]
Тогда такой вопрос: мы слотом можем делать любой метод или только метод QObject'a если только метод QObject'a, то я заведу класс Reciever(QObject) со слотами и добавлю его в SourceNode.

Вроде такого:

class Reciever(QObject):
    @pyqtSlot(tuple)
    def __init__(self, source):
        super().__init__()
        self.source = source

    def on_montageError(self, args):
        ch_names_source, ch_names_fwd, source_bads = args
        montage_menu = MontageMenu(source_ch_names=ch_names_source,
                                        forward_ch_names=ch_names_fwd, source_bads=source_bads, reciever=self)
        montage_menu.exec()

    @pyqtSlot(dict)
    def on_montageChanged(self, montage_mapping):
        self.source._remap(montage_mapping)

**Comment by dmalt** [comment]
Слот может быть где угодно, не только у QObject.  При этом декоратор pyqtSlot как правило использовать не обязательно. А вот сигнал может испускать только потомок QObject.

**Comment by logogriph2** [comment]
Ок, спасибо! Тогда логичнее слот делать в самом FileSource, но тогда при простом вызове меню montage_menu.exec() в этом методе он, видимо, создается в потоке, который что-то блокирует. Если создавать меню в методе qobject'a, работает нормально. Вопрос: как отключить блокировку потока, чтобы принимать сигнал в FileSource и надо ли это делать?

**Comment by dmalt** [comment]
Только не в FileSource а в SourceNode, потому что мы хотим и LSL источник уметь редактировать.
А что значит блокирует? Нельзя взаимодействовать с другими окнами? exec() запускает even-loop, а не поток, т.е. начинает обрабатывать всякие клики и прочие способы взаимодействия с окном. Там есть тонкости с тем, какое окно конкретно обслуживается запущенным event-loop-ом, но это надо конкретно смотреть.

**Comment by dmalt** [comment]
это может быть связано с выставлением правильного родителя монтажному меню

**Comment by dmalt** [comment]
Можно закрывать?
