### ISSUE TITLE
Проблемы запуска launch_cognigraph

### ISSUE THREAD

**Issue by FasT93** [Cognigraph/cognigraph#40]
- [ ] Программа крашится если остутствует папка анатомии (хорошо бы чтобы интерфейс выдавал ошибку и не падал при этом). 

- [x] Программа крашится если тыкнуть правой мышкой по белому полю (там где дерево пайплайна отрисовывается).

- [x] Нет возможности в дереве пайплайна добавить выходной поток LSL.

- [x] Программа падает если добавить какой-либо узел визуализации (например BrainViewer), затем закрыть окно с ним и нажать кнопку Start.

- [x] Программа падает если во время ее выполнения в настройках BrainViewerNode изменять параметр Limits.

- [x] Программа падает если во время ее выполнения в настройках BrainViewerNode нажать кнопку Record gif

- [x] Программа падает если во время ее выполнения в настройках BeamformerNode убрать флаг Use adaptive version.

- [x] Программа падает если в настройках BeamformerNode загрузить файл прямой модели (кнопка Select data...). Даже при загрузке того же самого файла что был загружен ранее.

- [x] Если уменьшить размер поля настроек (которое слева) и нажать на кнопку Start то размеры вернутся к дефолтным значениям. 

- [x] Программа падает при добавлении узла AtlasViewer в редакторе пайплайна.

- [x] При попытке добавить дополнительный узел Beamformer без загрузки модели, программа не падает, выдает окно с ошибкой и в логе пишет "if not fname.endswith(endings): AttributeError: 'NoneType' object has no attribute 'endswith'". Можно ли сделать сообщение об ошибке более информативным, например "Файл прямой модели не загружен." или брать файл прямой модели который уже был загружен при запуске программы?

- [x] Нет возможности удалить добавленный узел в пайплайне.

- [x] Нельзя добавить в узел Preprocessing узел LinearFilter.

**Comment by dmalt** [comment]
> Если уменьшить размер поля настроек (которое слева) и нажать на кнопку Start то размеры вернутся к дефолтным значениям.
У меня не воспроизводится. Можешь проверить еще раз, взяв последние изменения из ветки pipeline_editor?

**Comment by dmalt** [comment]
> Программа падает если в настройках BeamformerNode загрузить файл прямой модели (кнопка Select data...). Даже при загрузке того же самого файла что был загружен ранее.

Это тоже не воспроизвелось

**Comment by dmalt** [comment]
> Программа падает если во время ее выполнения в настройках BrainViewerNode изменять параметр Limits.

> Программа падает если во время ее выполнения в настройках BeamformerNode убрать флаг Use adaptive version.

Эти две ошибки -- следствие [бага](https://github.com/pyqtgraph/pyqtgraph/issues/263) pyqtgraph.
Баг поправлен в ветке develop pyqtgraph`a.

Чтобы починить, нужно ставить pyqtgraph из ветки develop на github:
```
git clone <pyqtgraph-repo-address> --branch develop
cd pyqtgraph
pip install .
```

Я поправлю environment.yml, чтобы нужная версия ставилась автоматически.

**Comment by FasT93** [comment]
> > Если уменьшить размер поля настроек (которое слева) и нажать на кнопку Start то размеры вернутся к дефолтным значениям.
> 
> У меня не воспроизводится. Можешь проверить еще раз, взяв последние изменения из ветки pipeline_editor?

Вот как у меня это выглядит
![problem1](https://user-images.githubusercontent.com/40063398/56270325-86245b00-60fe-11e9-8f46-54e943dcecd9.gif)

**Comment by FasT93** [comment]
> > Программа падает если во время ее выполнения в настройках BrainViewerNode изменять параметр Limits.
> 
> > Программа падает если во время ее выполнения в настройках BeamformerNode убрать флаг Use adaptive version.
> 
> Эти две ошибки -- следствие [бага](https://github.com/pyqtgraph/pyqtgraph/issues/263) pyqtgraph.
> Баг поправлен в ветке develop pyqtgraph`a.
> 
> Чтобы починить, нужно ставить pyqtgraph из ветки develop на github:
> 
> ```
> pip install git+https://github.com/pyqtgraph/pyqtgraph.git@develop 
> ```

Да, теперь работает

**Comment by FasT93** [comment]
> > Программа падает если в настройках BeamformerNode загрузить файл прямой модели (кнопка Select data...). Даже при загрузке того же самого файла что был загружен ранее.
> 
> Это тоже не воспроизвелось

В новой версии кода прога не падает, но при загрузке файла прямой модели на мозгах активные области больше не изменяются (на гифке видно)
![problem2](https://user-images.githubusercontent.com/40063398/56271974-60995080-6102-11e9-885c-dd9f066b2471.gif)

**Comment by FasT93** [comment]
При добавлении узла LSL Stream Output появляется табличка в которой можно задать имя выходного потока. Однако какое бы имя я не написал, имя выходного потока будет имя входного файла + '_output'

**Comment by dmalt** [comment]
> > > Программа падает если в настройках BeamformerNode загрузить файл прямой модели (кнопка Select data...). Даже при загрузке того же самого файла что был загружен ранее.
> > 
> > 
> > Это тоже не воспроизвелось
> 
> В новой версии кода прога не падает, но при загрузке файла прямой модели на мозгах активные области больше не изменяются (на гифке видно)
> ![problem2](https://user-images.githubusercontent.com/40063398/56271974-60995080-6102-11e9-885c-dd9f066b2471.gif)

Ты достаточно времени ждешь? При загрузге новой прямой модели ресетятся узлы, и это занимает примерно то же время как и на инициализацию в самом начале. Что происходит в логе в это время?

**Comment by FasT93** [comment]
В логе вот такая ошибка
File "F:\Cognigraph\cognigraph_v2_pipeline_editor_new\cognigraph\nodes\outputs.py", line 197, in _on_input_history_invalidation
    self.reset()
TypeError: reset() missing 1 required positional argument: 'is_input_hist_invalid'

**Comment by dmalt** [comment]
> > > Программа падает если в настройках BeamformerNode загрузить файл прямой модели (кнопка Select data...). Даже при загрузке того же самого файла что был загружен ранее.
> > 
> > 
> > Это тоже не воспроизвелось
> 
> В новой версии кода прога не падает, но при загрузке файла прямой модели на мозгах активные области больше не изменяются (на гифке видно)
> ![problem2](https://user-images.githubusercontent.com/40063398/56271974-60995080-6102-11e9-885c-dd9f066b2471.gif)

Починил

**Comment by dmalt** [comment]
> При добавлении узла LSL Stream Output появляется табличка в которой можно задать имя выходного потока. Однако какое бы имя я не написал, имя выходного потока будет имя входного файла + '_output'

И это починил
