### ISSUE TITLE
Проблема запуска launch_cognigraph

### ISSUE THREAD

**Issue by FasT93** [Cognigraph/cognigraph#42]
При попытке запустить новую версию когниграфа прога падает после выбора edf и fif файлов не выдавая никакой ошибки, только это: "Process finished with exit code -1073740791". С предыдущей версией был порядок в этом плане.

**Comment by dmalt** [comment]
Какой командой запускал?
Пишется ли в лог что-нибудь?

**Comment by FasT93** [comment]
launch_cognigraph, запускал как обычно - просто Run из pycharm. Вот скрин всего что мне выводится
![11](https://user-images.githubusercontent.com/40063398/56208281-7272e900-6059-11e9-9116-9ac6b02f4fab.png)

**Comment by dmalt** [comment]
Судя по логу, умирает на этапе отрисовки виджета с мозгами. Попробуй для начала перезагрузиться. Вряд ли конечно на винде в этом дело, но на линуксу иногда бывает, что видеокарта отваливается по неизваестной причине.

**Comment by dmalt** [comment]
Дальше нужно будет лезть в код и смотреть, какая именно строка вызывает смерть.
У меня на линуксе все работает ок, надо сказать, так что это либо что-то с версиями пакетов, либо с драйвером видеокарты.

**Comment by dmalt** [comment]
Кстати говоря, теперь из консоли должно быть возможно запускать программу просто командой `cognigraph` без указания полного путь, если все ставилось в соответствии с инструкцией из README.

**Comment by FasT93** [comment]
Перезагрузил, не помогло. Прошел дебаггом, падает на строчке 123 в async_pipeline_update.py - q.exec(QEventLoop.ExcludeUserInputEvents)

**Comment by dmalt** [comment]
А прогресс-бар при этом видно?
        3:58 PM, April 16, 2019, Dmitrii <notifications@github.com>:Перезагрузил, не помогло. Прошел дебаггом, падает на строчке 123 в async_pipeline_update.py - q.exec(QEventLoop.ExcludeUserInputEvents)

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

Sent from Yandex.Mail for mobile: http://m.ya.ru/ymail

**Comment by FasT93** [comment]
Да, но в какой-то момент он останавливается и все падает.

**Comment by dmalt** [comment]
Понятно. Можешь расставить несколько принтов в функции _initialize класса BrainViewer, чтобы  понять, на какой строке он падает там?q.exec ни о чем не говорит, т.к. она просто показывает прогресс-бар, пока инициализация крутится в параллельной ветке.

**Comment by FasT93** [comment]
Попробовал запустить cognigraph из терминала, тут ошибка вот такая:
Traceback (most recent call last):
  File "f:\cognigraph\cognigraph_v2_pipeline_editor_new\cognigraph\nodes\outputs.py", line 74, in _init_widget
    self.widget.pipeline_node = self
AttributeError: 'NoneType' object has no attribute 'pipeline_node'

**Comment by FasT93** [comment]
А в методе инициализации класса BrainViewer он падает после строки self.signal_sender.init_widget_sig.emit()

**Comment by dmalt** [comment]
А у тебя точно последняя версия кода?

**Comment by FasT93** [comment]
Сегодня только скачал, может ты еще что обновить успел? Сейчас еще раз на всякий загружу

**Comment by dmalt** [comment]
Сегодня было много обновлений.

**Comment by FasT93** [comment]
Да, обновил - заработало.. Видимо я в неудачный момент загрузил. Буду тестить дальше.

**Comment by dmalt** [comment]
Я ещё буду доливать код, так что следи за обновлениями в pull-реквесте.
